const WORLDS_DATA = [
  {
    "uid": "A-0001",
    "name": "PassageDesParanoramas",
    "source": "convolute-A.md",
    "raw": "{\n\nmeta {\n  genre: \"urban archaeology / commercial phantasmagoria\"\n  description: \"The covered passage as ur-form of commodity space: a glass-roofed, marble-paneled corridor where industrial luxury first crystallized into architecture. The passage is simultaneously street and interior, public and private, a world in miniature where the flaneur finds shelter and the merchant finds customers.\"\n}\n\nlocations {\n  location <PassageDesParanoramas> {\n    description: \"10 Boulevard Montmartre to 11 Rue Saint-Marc, Paris, 2nd arrondissement\"\n    coordinates: \"48.8715° N, 2.3428° E\"\n    constructed: \"1799\"\n  }\n  location <GlassRoof> {\n    within: <PassageDesParanoramas>\n    description: \"Iron-and-glass canopy flooding the marble corridor with diffused daylight\"\n  }\n  location <ShopFrontages> {\n    within: <PassageDesParanoramas>\n    description: \"Double row of elegant boutiques lining the corridor, each window a display of manufactured desire\"\n  }\n}\n\nentities {\n  entity <Flaneur> : social_type {\n    traits: [ambulatory, bourgeois, observational]\n    location: <PassageDesParanoramas>\n  }\n  entity <Commodity> : economic_object {\n    traits: [displayed, fetishized, phantasmagoric]\n    location: <ShopFrontages>\n  }\n  entity <Weather> : environmental_force {\n    traits: [sudden_rain, catalyst_of_entry]\n  }\n  entity <GasLight> : illumination_technology {\n    traits: [artificial, nocturnal, theatrical]\n    location: <GlassRoof>\n  }\n}\n\nrelations {\n  rel [takes_refuge_in](<Flaneur> -> <PassageDesParanoramas>)\n  rel [displays](<ShopFrontages> -> <Commodity>)\n  rel [drives_into](<Weather> -> <Flaneur>)\n  rel [illuminates](<GasLight> -> <Commodity>)\n  rel [collapses_boundary_between](<PassageDesParanoramas> -> <Street_and_Interior>)\n}\n\nstates {\n  state <PassageDesParanoramas.function> = \"world_in_miniature\"\n  state <Commodity.status> = \"fetishized\"\n  state <Flaneur.posture> = \"ambulatory_observation\"\n}\n\nevents {\n  event <SuddenRainshower> {\n    actors: [<Weather>, <Flaneur>]\n    effects: [<Flaneur> enters <PassageDesParanoramas>, commerce_intensifies]\n  }\n}\n\ntimeline {\n  time <JulyMonarchy> {\n    description: \"1830-1848: peak era of the arcades before Haussmann's boulevards displaced them\"\n  }\n}\n\n}",
    "meta": {
      "genre": "urban archaeology / commercial phantasmagoria",
      "description": "The covered passage as ur-form of commodity space: a glass-roofed, marble-paneled corridor where industrial luxury first crystallized into architecture."
    }
  },
  {
    "uid": "A-0002",
    "name": "IronAndGlassConstruction",
    "source": "convolute-A.md",
    "raw": "{\n\nmeta {\n  genre: \"architectural materialism\"\n  description: \"The moment iron-and-glass construction made the dream of the passage possible. Iron freed architecture from the stone wall; glass dissolved the boundary between interior and sky. Together they produced spaces that were neither outdoors nor indoors — the first truly modern architecture, born in commerce, not in art.\"\n}\n\nlocations {\n  location <GalerieVivienne> {\n    description: \"6 Rue Vivienne, Paris. Built 1823. Neoclassical mosaic floor, Pompeian columns, rotunda skylight\"\n    coordinates: \"48.8685° N, 2.3389° E\"\n  }\n  location <GalerieColbert> {\n    description: \"6 Rue des Petits-Champs. Rival passage built 1826, featuring a great glass rotunda\"\n    coordinates: \"48.8678° N, 2.3392° E\"\n  }\n}\n\nentities {\n  entity <Iron> : construction_material {\n    traits: [industrial, tensile, prefabricated]\n  }\n  entity <Glass> : construction_material {\n    traits: [transparent, fragile, light_admitting]\n  }\n  entity <StoneWall> : construction_material {\n    traits: [traditional, load_bearing, opaque]\n  }\n  entity <Skylight> : architectural_element {\n    traits: [overhead, diffusing, utopian]\n    location: <GalerieVivienne>\n  }\n}\n\nrelations {\n  rel [liberates_from](<Iron> -> <StoneWall>)\n  rel [dissolves](<Glass> -> <Boundary_Interior_Sky>)\n  rel [combines_with](<Iron> -> <Glass>)\n  rel [produces](<Iron_and_Glass> -> <ModernArchitecture>)\n}\n\nstates {\n  state <Iron.origin> = \"industrial_not_artistic\"\n  state <Glass.function> = \"dematerialization_of_enclosure\"\n  state <ModernArchitecture.birthplace> = \"commerce\"\n}\n\nevents {\n  event <MaterialRevolution> {\n    actors: [<Iron>, <Glass>]\n    effects: [\"architecture freed from masonry\", \"interior-exterior boundary dissolved\"]\n  }\n}\n\ntimeline {\n  time <IndustrialRevolution> {\n    description: \"1820s-1850s: iron-and-glass construction enables the passage, the railway station, the exhibition hall\"\n  }\n}\n\n}",
    "meta": {
      "genre": "architectural materialism",
      "description": "The moment iron-and-glass construction made the dream of the passage possible. Iron freed architecture from the stone wall; glass dissolved the boundary between interior and sky."
    }
  },
  {
    "uid": "A-0003",
    "name": "MagasinsDeNouveautes",
    "source": "convolute-A.md",
    "raw": "{\n\nmeta {\n  genre: \"commercial mythology\"\n  description: \"The department stores that cannibalized the arcades. Named with theatrical fantasy — La Fille d'Honneur, Le Masque de Fer, Le Petit Chaperon Rouge — each store drew its name from successful vaudevilles, dressing commerce in the costume of popular mythology. The commodity demanded a stage name.\"\n}\n\nlocations {\n  location <BonMarche> {\n    description: \"24 Rue de Sèvres, Paris. Founded 1838, rebuilt 1869 by Gustave Eiffel and Louis-Charles Boileau\"\n    coordinates: \"48.8500° N, 2.3258° E\"\n  }\n  location <GrandsBoulevardsStorefront> {\n    description: \"The boulevard-facing display windows that replaced the passage's interior shops\"\n  }\n}\n\nentities {\n  entity <DepartmentStore> : commercial_institution {\n    traits: [theatrical, totalizing, phantasmagoric]\n    location: <BonMarche>\n  }\n  entity <SalesClerk> : labor_figure {\n    traits: [performative, surveilled, feminized]\n    location: <BonMarche>\n  }\n  entity <VaudevilleName> : cultural_signifier {\n    traits: [theatrical, mythological, borrowed]\n  }\n  entity <DisplayWindow> : interface {\n    traits: [transparent, seductive, commodifying]\n    location: <GrandsBoulevardsStorefront>\n  }\n}\n\nrelations {\n  rel [cannibalizes](<DepartmentStore> -> <Arcade>)\n  rel [borrows_name_from](<DepartmentStore> -> <VaudevilleName>)\n  rel [displays_through](<Commodity> -> <DisplayWindow>)\n  rel [performs_in](<SalesClerk> -> <DepartmentStore>)\n}\n\nstates {\n  state <DepartmentStore.naming_convention> = \"theatrical_fantasy\"\n  state <SalesClerk.condition> = \"commodity_themselves\"\n  state <Arcade.status> = \"declining\"\n}\n\nevents {\n  event <CommercialDisplacement> {\n    actors: [<DepartmentStore>, <Arcade>]\n    effects: [\"passage commerce migrates to boulevard\", \"interior shopping yields to storefront display\"]\n  }\n}\n\ntimeline {\n  time <SecondEmpire> {\n    description: \"1852-1870: Haussmann's boulevards and the rise of the grands magasins displace the arcades\"\n  }\n}\n\n}",
    "meta": {
      "genre": "commercial mythology",
      "description": "The department stores that cannibalized the arcades. Named with theatrical fantasy from successful vaudevilles, dressing commerce in the costume of popular mythology."
    }
  },
  {
    "uid": "A-0004",
    "name": "PhantasmagoriaOfTheMarketplace",
    "source": "convolute-A.md",
    "raw": "{\n\nmeta {\n  genre: \"critical theory / commodity fetishism\"\n  description: \"The phantasmagoria: Marx's term for the process by which commodities conceal their origin in human labor. Benjamin extends this to architecture, fashion, and the city itself. The arcade is the original phantasmagoria — a space where manufactured objects appear to glow with autonomous life, where the glass roof creates a dreamlike interiority, where commerce presents itself as nature.\"\n}\n\nlocations {\n  location <ArcadeInterior> {\n    description: \"Any passage: the marble floor, the gas-lit vitrines, the iron columns disguised as classical pilasters\"\n  }\n}\n\nentities {\n  entity <Phantasmagoria> : critical_concept {\n    traits: [Marxian, optical, concealing]\n  }\n  entity <CommodityFetish> : critical_concept {\n    traits: [Marxian, relational, mystifying]\n  }\n  entity <UseValue> : economic_category {\n    traits: [material, concealed, labor_derived]\n  }\n  entity <ExchangeValue> : economic_category {\n    traits: [abstract, visible, autonomous_seeming]\n  }\n  entity <DreamCollective> : social_subject {\n    traits: [sleeping, nineteenth_century, bourgeois]\n    location: <ArcadeInterior>\n  }\n}\n\nrelations {\n  rel [conceals](<Phantasmagoria> -> <UseValue>)\n  rel [presents_as_natural](<Phantasmagoria> -> <ExchangeValue>)\n  rel [dreams_in](<DreamCollective> -> <ArcadeInterior>)\n  rel [is_instance_of](<ArcadeInterior> -> <Phantasmagoria>)\n  rel [extends](<Benjamin> -> <CommodityFetish>)\n}\n\nstates {\n  state <DreamCollective.consciousness> = \"asleep\"\n  state <Phantasmagoria.mechanism> = \"commodity_appears_autonomous\"\n  state <UseValue.visibility> = \"concealed_by_display\"\n}\n\nrules {\n  rule <DialecticalImage> {\n    if:\n      - <DreamCollective> encounters <Phantasmagoria>\n      - <Critic> reveals <UseValue> beneath <ExchangeValue>\n    then:\n      - event <Awakening>\n  }\n}\n\nevents {\n  event <Awakening> {\n    actors: [<DreamCollective>, <Critic>]\n    effects: [\"phantasmagoria dissolves\", \"labor becomes visible behind the commodity\"]\n  }\n}\n\ntimeline {\n  time <NineteenthCentury> {\n    description: \"The century of the dream collective, the commodity fetish, and the phantasmagoria of progress\"\n  }\n}\n\n}",
    "meta": {
      "genre": "critical theory / commodity fetishism",
      "description": "The phantasmagoria: Marx's concept extended by Benjamin to architecture, fashion, and the city. The arcade as the space where commodities conceal their origin in labor."
    }
  },
  {
    "uid": "J-0001",
    "name": "BaudelaireAllegoristOfModernity",
    "source": "convolute-J.md",
    "raw": "{\n\nmeta {\n  genre: \"literary theory / modernism\"\n  description: \"For the first time, with Baudelaire, Paris becomes the subject of lyric poetry. This poetry is no pastoral. It gazes at the city with the eyes of an alienated man. The gaze of the allegorist that falls upon the city is the gaze of the estranged. It is the gaze of the flaneur whose mode of life still conceals behind a mitigating nimbus the coming desolation of the city-dweller.\"\n}\n\nlocations {\n  location <ParisStreets> {\n    description: \"The boulevards, the arcades, the Seine embankments — Baudelaire's Paris is not a setting but a protagonist\"\n  }\n  location <GarretRoom> {\n    description: \"Baudelaire's various rented rooms, each smaller and dingier than the last. The poet's workspace where the city enters through the window.\"\n  }\n}\n\nentities {\n  entity <Baudelaire> : poet {\n    traits: [allegorist, flaneur, estranged, indebted]\n    location: <GarretRoom>\n  }\n  entity <Paris> : city_as_subject {\n    traits: [modern, lyric_subject, phantasmagoric]\n  }\n  entity <Allegory> : literary_mode {\n    traits: [Baroque, ruin_gazing, meaning_draining]\n  }\n  entity <Spleen> : affective_condition {\n    traits: [melancholic, temporal, modern]\n  }\n  entity <LesSeptVieillards> : poem {\n    traits: [hallucinatory, multiplied_identity, urban_horror]\n  }\n}\n\nrelations {\n  rel [makes_subject_of_lyric](<Baudelaire> -> <Paris>)\n  rel [sees_through](<Baudelaire> -> <Allegory>)\n  rel [suffers_from](<Baudelaire> -> <Spleen>)\n  rel [drains_meaning_from](<Allegory> -> <Commodity>)\n  rel [heralds](<LesSeptVieillards> -> <Modernity>)\n}\n\nstates {\n  state <Baudelaire.gaze> = \"allegorical_estrangement\"\n  state <Paris.status> = \"first_lyric_city\"\n  state <Allegory.function> = \"ruins_meaning_to_reveal_truth\"\n}\n\nevents {\n  event <LyricModernity> {\n    actors: [<Baudelaire>, <Paris>]\n    effects: [\"city becomes lyric subject\", \"pastoral gaze replaced by urban melancholy\"]\n  }\n}\n\ntimeline {\n  time <FleursDuMal> {\n    description: \"1857: Les Fleurs du Mal published. Prosecuted for obscenity. The city enters poetry.\"\n    date: \"1857\"\n  }\n}\n\n}",
    "meta": {
      "genre": "literary theory / modernism",
      "description": "For the first time, with Baudelaire, Paris becomes the subject of lyric poetry. The gaze of the allegorist that falls upon the city is the gaze of the estranged."
    }
  },
  {
    "uid": "J-0002",
    "name": "TheHeroOfModernLife",
    "source": "convolute-J.md",
    "raw": "{\n\nmeta {\n  genre: \"aesthetic theory / labor\"\n  description: \"Baudelaire's hero is not the warrior or the saint but the person who endures modernity. The ragpicker, the prostitute, the apache — figures of the social margin who perform the labor that the city refuses to acknowledge. The poet himself is a ragpicker, collecting the debris of the city and reassembling it into verse. Both the poet and the ragpicker work at night with the refuse of the day.\"\n}\n\nlocations {\n  location <DawnStreets> {\n    description: \"Paris at 4 AM, when the ragpickers begin their rounds and the gas lamps gutter out\"\n  }\n  location <WineBarFaubourg> {\n    description: \"The barrière taverns where the working poor drink tax-free wine beyond the city walls\"\n  }\n}\n\nentities {\n  entity <Ragpicker> : social_type {\n    traits: [nocturnal, collecting, marginal, cataloguing]\n    location: <DawnStreets>\n  }\n  entity <Prostitute> : social_type {\n    traits: [commodified, nocturnal, allegorical]\n    location: <DawnStreets>\n  }\n  entity <Apache> : social_type {\n    traits: [criminal, urban, resistant]\n  }\n  entity <PoetAsRagpicker> : critical_analogy {\n    traits: [Baudelairean, productive, nocturnal]\n  }\n  entity <ModernHeroism> : concept {\n    traits: [anti_classical, urban, exhausted]\n  }\n}\n\nrelations {\n  rel [analogous_to](<Ragpicker> -> <PoetAsRagpicker>)\n  rel [collects_refuse_of](<Ragpicker> -> <City>)\n  rel [reassembles_into](<PoetAsRagpicker> -> <Verse>)\n  rel [embodies](<Ragpicker> -> <ModernHeroism>)\n  rel [embodies](<Prostitute> -> <CommodityForm>)\n}\n\nstates {\n  state <Ragpicker.labor> = \"cataloguing_urban_debris\"\n  state <PoetAsRagpicker.labor> = \"cataloguing_urban_debris_into_verse\"\n  state <ModernHeroism.character> = \"endurance_not_triumph\"\n}\n\nevents {\n  event <NocturnalCollection> {\n    actors: [<Ragpicker>, <PoetAsRagpicker>]\n    effects: [\"city's refuse becomes material\", \"verse composed from debris\"]\n  }\n}\n\ntimeline {\n  time <SecondEmpireParis> {\n    description: \"1850s-1860s: Baudelaire's Paris, Haussmann's demolitions, the marginal figures of the city\"\n  }\n}\n\n}",
    "meta": {
      "genre": "aesthetic theory / labor",
      "description": "The ragpicker, the prostitute, the apache — Baudelaire's heroes of modern life. The poet himself is a ragpicker, collecting the debris of the city and reassembling it into verse."
    }
  },
  {
    "uid": "J-0003",
    "name": "CorrespondancesAndShock",
    "source": "convolute-J.md",
    "raw": "{\n\nmeta {\n  genre: \"sensory theory / urban psychology\"\n  description: \"Baudelaire's correspondances — the doctrine that sensory impressions echo across modalities (a color has a scent, a sound has a texture) — represent the remnant of an archaic experience that modernity is destroying. The shock experience of the modern city (crowds, traffic, industrial noise) fragments perception. Correspondances name what is being lost; shock names the mechanism of destruction.\"\n}\n\nlocations {\n  location <BoulevardCrowd> {\n    description: \"The great Haussmann boulevards at rush hour: a torrent of bodies, vehicles, and sensory assault\"\n  }\n  location <TempleOfNature> {\n    description: \"The imagined pre-modern sensorium where 'living pillars' speak in 'confused words' — Baudelaire's Correspondances sonnet\"\n  }\n}\n\nentities {\n  entity <Correspondances> : poetic_doctrine {\n    traits: [synaesthetic, archaic, endangered]\n  }\n  entity <ShockExperience> : perceptual_condition {\n    traits: [modern, fragmenting, defensive]\n  }\n  entity <Aura> : perceptual_quality {\n    traits: [distance, cult_value, withering]\n  }\n  entity <MemoryVoluntaire> : cognitive_mode {\n    traits: [conscious, impoverished, modern]\n  }\n  entity <MemoireInvolontaire> : cognitive_mode {\n    traits: [Proustian, involuntary, archaic]\n  }\n}\n\nrelations {\n  rel [destroys](<ShockExperience> -> <Correspondances>)\n  rel [withers](<ShockExperience> -> <Aura>)\n  rel [replaces](<MemoryVoluntaire> -> <MemoireInvolontaire>)\n  rel [names_loss_of](<Correspondances> -> <Aura>)\n  rel [defends_against](<Consciousness> -> <ShockExperience>)\n}\n\nstates {\n  state <Correspondances.status> = \"remnant_of_archaic_experience\"\n  state <ShockExperience.mechanism> = \"fragmentation_of_perception\"\n  state <Aura.condition> = \"withering_in_modernity\"\n}\n\nrules {\n  rule <ShockDefense> {\n    if:\n      - <ShockExperience> overwhelms <Consciousness>\n    then:\n      - event <PerceptualArmoring>\n  }\n}\n\nevents {\n  event <PerceptualArmoring> {\n    actors: [<Consciousness>, <ShockExperience>]\n    effects: [\"experience impoverished\", \"correspondances inaccessible\", \"aura decays\"]\n  }\n}\n\ntimeline {\n  time <EraOfMechanicalReproduction> {\n    description: \"The epoch when shock replaces contemplation as the dominant mode of perception\"\n  }\n}\n\n}",
    "meta": {
      "genre": "sensory theory / urban psychology",
      "description": "Correspondances name what modernity is destroying; shock names the mechanism of destruction. The fragmentation of perception under the assault of the modern city."
    }
  },
  {
    "uid": "M-0001",
    "name": "TheFlaneurAsReader",
    "source": "convolute-M.md",
    "raw": "{\n\nmeta {\n  genre: \"urban epistemology\"\n  description: \"The flaneur reads the city as a text. Every storefront is a page, every passerby a character, every street corner a paragraph break. But this is not idle strolling. The flaneur's gaze is physiognomic — it reads faces, surfaces, and arrangements for their social content. Benjamin: the flaneur is the priest of the genius loci.\"\n}\n\nlocations {\n  location <Boulevard> {\n    description: \"The broad Haussmann avenue: the flaneur's reading room, where the crowd becomes a text\"\n  }\n  location <ArcadeAsLivingRoom> {\n    description: \"The passage serves the flaneur as living room. The walls are his bookshelves, the terraces his balcony.\"\n  }\n}\n\nentities {\n  entity <Flaneur> : social_type {\n    traits: [reader, physiognomist, priest_of_genius_loci]\n    location: <Boulevard>\n  }\n  entity <Crowd> : social_formation {\n    traits: [urban, anonymous, text_like]\n    location: <Boulevard>\n  }\n  entity <PhysiognomicGaze> : perceptual_mode {\n    traits: [reading, surface_scanning, social_decoding]\n  }\n  entity <Tortoise> : accessory {\n    traits: [pace_setting, legendary, oppositional]\n    description: \"The flaneur was said to take turtles for a walk in the arcades, letting them set the pace. The pace of the flaneur is the counter-rhythm to industrial speed.\"\n  }\n}\n\nrelations {\n  rel [reads](<Flaneur> -> <City>)\n  rel [employs](<Flaneur> -> <PhysiognomicGaze>)\n  rel [inhabits](<Flaneur> -> <ArcadeAsLivingRoom>)\n  rel [resists_via](<Flaneur> -> <Tortoise>)\n  rel [opposes](<Tortoise> -> <IndustrialSpeed>)\n}\n\nstates {\n  state <Flaneur.activity> = \"reading_the_city\"\n  state <City.status> = \"text_to_be_deciphered\"\n  state <Tortoise.function> = \"counter_rhythm\"\n}\n\nevents {\n  event <Flânerie> {\n    actors: [<Flaneur>, <City>]\n    effects: [\"city becomes legible\", \"physiognomic knowledge produced\", \"industrial time resisted\"]\n  }\n}\n\ntimeline {\n  time <JulyMonarchy> {\n    description: \"1830-1848: the golden age of the flaneur, before Haussmann's demolitions and the department store displaced ambulatory reading\"\n  }\n}\n\n}",
    "meta": {
      "genre": "urban epistemology",
      "description": "The flaneur reads the city as a text. Every storefront is a page, every passerby a character. The tortoise sets the pace against industrial speed."
    }
  },
  {
    "uid": "M-0002",
    "name": "FlaneurBecomesDetective",
    "source": "convolute-M.md",
    "raw": "{\n\nmeta {\n  genre: \"literary sociology / surveillance\"\n  description: \"The flaneur's gaze intensifies into detection. Poe's Man of the Crowd is the transitional text: the narrator follows a stranger through London's streets, reading his surface for criminal clues. The detective novel is born when the city becomes too large to be known by walking. Detection replaces flânerie when physiognomic knowledge fails — when the face no longer reveals the person.\"\n}\n\nlocations {\n  location <LondonCrowdScene> {\n    description: \"Poe's London coffee-house window, looking out at the evening crowd: the site where observation becomes pursuit\"\n  }\n  location <ParisPoliceArchive> {\n    description: \"The Préfecture de Police, Ile de la Cité. The archive of criminal photography, Bertillon measurements, and bureaucratic identification\"\n  }\n}\n\nentities {\n  entity <FlaneurDetective> : social_type {\n    traits: [pursuing, suspicious, reading_surfaces]\n  }\n  entity <ManOfTheCrowd> : literary_text {\n    traits: [Poe, transitional, London]\n    date: \"1840\"\n  }\n  entity <DetectiveNovel> : genre {\n    traits: [born_of_urban_illegibility, compensatory]\n  }\n  entity <BertillonSystem> : identification_technology {\n    traits: [bureaucratic, photographic, measuring]\n    location: <ParisPoliceArchive>\n  }\n  entity <PhysiognomicFailure> : epistemic_crisis {\n    traits: [urban, modern, anonymity_producing]\n  }\n}\n\nrelations {\n  rel [intensifies_into](<Flaneur> -> <FlaneurDetective>)\n  rel [narrates](<ManOfTheCrowd> -> <Transition_Flanerie_Detection>)\n  rel [compensates_for](<DetectiveNovel> -> <PhysiognomicFailure>)\n  rel [replaces_physiognomy_with](<BertillonSystem> -> <Bureaucratic_Measurement>)\n  rel [produces](<UrbanAnonymity> -> <PhysiognomicFailure>)\n}\n\nstates {\n  state <Flaneur.trajectory> = \"observation_becomes_pursuit\"\n  state <City.legibility> = \"declining\"\n  state <DetectiveNovel.function> = \"compensatory_knowledge\"\n}\n\nevents {\n  event <BirthOfDetection> {\n    actors: [<FlaneurDetective>, <PhysiognomicFailure>]\n    effects: [\"walking becomes following\", \"reading becomes investigation\", \"urban knowledge bureaucratized\"]\n  }\n}\n\ntimeline {\n  time <MidCenturyTransition> {\n    description: \"1840s-1860s: the flaneur becomes the detective as the city exceeds physiognomic knowledge\"\n  }\n}\n\n}",
    "meta": {
      "genre": "literary sociology / surveillance",
      "description": "The flaneur's gaze intensifies into detection. Poe's Man of the Crowd is the transitional text. The detective novel is born when the city becomes too large to be known by walking."
    }
  },
  {
    "uid": "M-0003",
    "name": "FlaneurAndTheCrowd",
    "source": "convolute-M.md",
    "raw": "{\n\nmeta {\n  genre: \"social psychology / political economy\"\n  description: \"The crowd is the flaneur's element, as the air is the bird's. But the crowd is also the veil through which the familiar city beckons to the flaneur as phantasmagoria. The flaneur's relationship to the crowd is ambivalent: intoxication and resistance. He moves with the crowd but against its tempo. He uses the crowd as cover. The crowd is both his habitat and his antagonist.\"\n}\n\nlocations {\n  location <GrandsBoulevards> {\n    description: \"Boulevard des Italiens, Boulevard Montmartre, Boulevard Poissonnière — the continuous promenade of the nineteenth-century crowd\"\n  }\n}\n\nentities {\n  entity <Crowd> : social_formation {\n    traits: [anonymous, flowing, phantasmagoric, veil_like]\n    location: <GrandsBoulevards>\n  }\n  entity <Flaneur> : social_type {\n    traits: [ambulatory, intoxicated, resistant]\n    location: <GrandsBoulevards>\n  }\n  entity <Intoxication> : affective_state {\n    traits: [hashish_like, urban, perceptual]\n  }\n  entity <Empathy> : perceptual_mode {\n    traits: [with_commodity, with_crowd, with_city]\n    description: \"The flaneur's empathy with the commodity: he enters the soul of the merchandise as the customer enters the store\"\n  }\n  entity <Sandwich_Board_Man> : social_type {\n    traits: [ambulatory_advertisement, commodified_human, degraded_flaneur]\n    location: <GrandsBoulevards>\n  }\n}\n\nrelations {\n  rel [bathes_in](<Flaneur> -> <Crowd>)\n  rel [uses_as_veil](<Flaneur> -> <Crowd>)\n  rel [empathizes_with](<Flaneur> -> <Commodity>)\n  rel [degrades_into](<Flaneur> -> <Sandwich_Board_Man>)\n  rel [produces](<Crowd> -> <Phantasmagoria>)\n}\n\nstates {\n  state <Flaneur.relationship_to_crowd> = \"intoxication_and_resistance\"\n  state <Crowd.function> = \"habitat_and_antagonist\"\n  state <Sandwich_Board_Man.status> = \"final_form_of_flaneur\"\n}\n\nrules {\n  rule <FlaneurDegradation> {\n    if:\n      - <Market> demands <Flaneur.labor>\n      - <Flaneur> has no buyer\n    then:\n      - event <MarketForced_Flânerie>\n  }\n}\n\nevents {\n  event <MarketForced_Flânerie> {\n    actors: [<Flaneur>, <Market>]\n    effects: [\"flaneur becomes sandwich-board man\", \"ambulatory observation becomes ambulatory advertisement\"]\n  }\n}\n\ntimeline {\n  time <LateSecondEmpire> {\n    description: \"1860s-1870s: the flaneur's degradation from bourgeois observer to proletarianized advertisement\"\n  }\n}\n\n}",
    "meta": {
      "genre": "social psychology / political economy",
      "description": "The crowd is the flaneur's element. But the crowd is also the veil through which the familiar city beckons as phantasmagoria. The flaneur's final form: the sandwich-board man."
    }
  },
  {
    "uid": "D-0001",
    "name": "EternalReturnAsHell",
    "source": "convolute-D.md",
    "raw": "{\n\nmeta {\n  genre: \"temporal philosophy / cosmology of modernity\"\n  description: \"Blanqui's L'Éternité par les Astres — written in the prison fortress of Taureau during the Commune — proposes that the universe endlessly repeats itself. Every human being exists in infinite copies. This resignation without hope is the last word of the great revolutionary. The century's final phantasmagoria: progress itself is the eternal return of the same.\"\n}\n\nlocations {\n  location <FortDuTaureau> {\n    description: \"Island fortress off the coast of Brittany, where Blanqui was imprisoned during the Paris Commune, 1871\"\n    coordinates: \"48.6833° N, 3.8833° W\"\n  }\n  location <CosmicStage> {\n    description: \"The universe as narrow stage — a noisy humanity infatuated with its own grandeur, living in its prison as though in some immense realm\"\n  }\n}\n\nentities {\n  entity <Blanqui> : revolutionary {\n    traits: [imprisoned, resigned, cosmological]\n    location: <FortDuTaureau>\n  }\n  entity <EternalReturn> : philosophical_concept {\n    traits: [Blanquian, Nietzschean, hellish]\n  }\n  entity <Progress> : ideological_concept {\n    traits: [phantasmagoric, fraudulent, circular]\n  }\n  entity <LeMemeMonotone> : condition {\n    traits: [repetition, immobility, cosmic]\n    description: \"The same monotony, the same immobility, on other heavenly bodies. The universe repeats itself endlessly and paws the ground in place.\"\n  }\n  entity <Doubles> : metaphysical_condition {\n    traits: [infinite, flesh_and_bone, eternal]\n    description: \"These doubles exist in flesh and bone — in trousers and jacket, in crinoline and chignon. They are by no means phantoms; they are the present eternalized.\"\n  }\n}\n\nrelations {\n  rel [writes_in](<Blanqui> -> <FortDuTaureau>)\n  rel [proposes](<Blanqui> -> <EternalReturn>)\n  rel [is_phantasmagoria_of](<Progress> -> <EternalReturn>)\n  rel [predates](<Blanqui> -> <Nietzsche.Zarathustra>)\n  rel [produces](<EternalReturn> -> <Doubles>)\n}\n\nstates {\n  state <Blanqui.condition> = \"resignation_without_hope\"\n  state <Progress.true_nature> = \"eternal_return_of_the_same\"\n  state <Century.final_phantasmagoria> = \"progress_itself\"\n}\n\nevents {\n  event <CosmicResignation> {\n    actors: [<Blanqui>]\n    effects: [\"revolutionary energy exhausted\", \"progress revealed as repetition\", \"hell is not punishment but monotony\"]\n  }\n}\n\ntimeline {\n  time <ParisCommune> {\n    description: \"1871: Blanqui imprisoned during the Commune. The revolutionary writes cosmology. L'Éternité par les Astres published 1872.\"\n    date: \"1872\"\n  }\n}\n\n}",
    "meta": {
      "genre": "temporal philosophy / cosmology of modernity",
      "description": "Blanqui's eternal return: written in prison during the Commune. The century's final phantasmagoria — progress itself is the eternal return of the same. Resignation without hope is the last word of the great revolutionary."
    }
  },
  {
    "uid": "H-0001",
    "name": "TheCollectorAsAllegorist",
    "source": "convolute-H.md",
    "raw": "{\n\nmeta {\n  genre: \"material culture / psychology of possession\"\n  description: \"The collector detaches the object from its functional context. Freed from the obligation to be useful, the object enters a new order — the collection — where its value is determined by proximity to other objects, by completeness, by rarity. The collector is the true resident of the interior. The collection is a form of practical memory. It is also a protest against the commodity: by removing the object from circulation, the collector reverses the commodity's destiny.\"\n}\n\nlocations {\n  location <BourgeoisInterior> {\n    description: \"The plush, overstuffed apartment of the Second Empire: velvet curtains, étagères, display cases. The interior as the universe of the private citizen.\"\n  }\n  location <DisplayCase> {\n    within: <BourgeoisInterior>\n    description: \"The glass-enclosed cabinet where objects are arranged not by function but by affinity\"\n  }\n}\n\nentities {\n  entity <Collector> : social_type {\n    traits: [allegorist, interior_dweller, anti_commodity]\n  }\n  entity <Collection> : system {\n    traits: [decontextualized, reordered, memorial]\n    location: <DisplayCase>\n  }\n  entity <Object> : material_thing {\n    traits: [detached_from_function, re_valued, proximate]\n  }\n  entity <CommodityCirculation> : economic_process {\n    traits: [functional, exchangeable, impersonal]\n  }\n  entity <PracticalMemory> : cognitive_mode {\n    traits: [material, spatial, associative]\n  }\n}\n\nrelations {\n  rel [detaches_from_function](<Collector> -> <Object>)\n  rel [enters](<Object> -> <Collection>)\n  rel [reverses](<Collection> -> <CommodityCirculation>)\n  rel [constitutes](<Collection> -> <PracticalMemory>)\n  rel [dwells_in](<Collector> -> <BourgeoisInterior>)\n}\n\nstates {\n  state <Object.value_source> = \"proximity_and_completeness\"\n  state <Collection.function> = \"protest_against_commodity\"\n  state <Collector.posture> = \"allegorical_rescue\"\n}\n\nevents {\n  event <AllegoricalRescue> {\n    actors: [<Collector>, <Object>]\n    effects: [\"object freed from use-value\", \"new meaning assigned by arrangement\", \"commodity circulation interrupted\"]\n  }\n}\n\ntimeline {\n  time <SecondEmpire> {\n    description: \"1852-1870: the golden age of the collector, the bourgeois interior, and the protest of the object against its commodification\"\n  }\n}\n\n}",
    "meta": {
      "genre": "material culture / psychology of possession",
      "description": "The collector detaches the object from its functional context, entering it into a new order. The collection is a form of practical memory and a protest against the commodity."
    }
  }
];
